'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight, ChevronLeft, ChevronRight, Clock3, Flame, Mail, Star } from 'lucide-react'
import { articles, hero, trending } from '@/data/articles'
import { popularGames, reviews, upcomingGames, type Game } from '@/data/games'

const img = (src:string) => src

export function FeaturedHero(){ return <section className="hero-grid wrap"><Link href={hero.href} className="hero-card group"><Image src={img(hero.image)} alt={hero.title} fill sizes="(max-width: 900px) 100vw, 66vw" priority className="object-cover transition duration-700 group-hover:scale-105"/><div className="hero-shade"/><div className="hero-copy"><span className="eyebrow accent">{hero.category}</span><h1>{hero.title}</h1><p>{hero.excerpt}</p><div className="meta"><span>{hero.author}</span><span>•</span><span>{hero.date}</span><span className="read-link">Read story <ArrowUpRight size={16}/></span></div></div></Link><div className="side-stories">{articles.slice(1,3).map(a=><Link href={a.href} className="side-story group" key={a.id}><Image src={a.image} alt="" fill sizes="(max-width: 900px) 100vw, 34vw" className="object-cover transition duration-500 group-hover:scale-105"/><div className="story-shade"/><div><span className="eyebrow accent">{a.category}</span><h2>{a.title}</h2><span className="muted">{a.time}</span></div></Link>)}</div></section> }

export function ArticleCard({article, compact=false}:{article: typeof articles[number], compact?:boolean}){ return <Link href={article.href} className={`article-card group ${compact?'compact':''}`}><div className="thumb"><Image src={article.image} alt={article.title} fill sizes="(max-width: 640px) 100vw, 300px" className="object-cover transition duration-500 group-hover:scale-105"/></div><div className="article-body"><span className="eyebrow accent">{article.category}</span><h3>{article.title}</h3>{!compact&&<p>{article.excerpt}</p>}<span className="time"><Clock3 size={13}/>{article.time}</span></div></Link> }
export function LatestNews(){ return <section className="wrap section"><SectionHead title="Latest News" href="/news"/><div className="news-grid">{articles.slice(1).map(a=><ArticleCard article={a} key={a.id}/>)}</div></section> }
export function Trending(){ return <section className="trend-section"><div className="wrap section"><SectionHead title="Trending now" label="THE FEED"/><div className="trend-list">{trending.map((a,i)=><Link href={a.href} className="trend-item group" key={a.id}><span className="rank">0{i+1}</span><div className="trend-thumb"><Image src={a.image} alt="" fill sizes="100px" className="object-cover transition group-hover:scale-110"/></div><div><span className="eyebrow accent">{a.category}</span><h3>{a.title}</h3><span className="muted">{a.time}</span></div><ArrowUpRight className="trend-arrow" size={18}/></Link>)}</div></div></section> }
export function GameCard({game, upcoming=false}:{game:Game;upcoming?:boolean}){return <Link href={`/game/${game.id}`} className="game-card group"><div className="game-image"><Image src={game.image} alt={game.title} fill sizes="240px" className="object-cover transition duration-500 group-hover:scale-105"/>{game.days&&<b className="days">{game.days}</b>}{game.rating&&<b className="rating">{game.rating}</b>}</div><div className="game-info"><h3>{game.title}</h3><div className="game-meta"><span>{game.genre}</span><span>{game.platforms.join(' / ')}</span></div><p>{upcoming?game.release:game.release}</p></div></Link>}
export function Upcoming(){return <section className="wrap section"><SectionHead title="Upcoming games" label="MARK YOUR CALENDAR" controls/><div className="rail">{upcomingGames.map(g=><GameCard game={g} upcoming key={g.id}/>)}</div></section>}
export function Reviews(){return <section className="review-section"><div className="wrap section"><SectionHead title="Reviews" href="/reviews" label="THE VERDICT"/><div className="review-grid">{reviews.map(r=><Link href={`/game/${r.id}`} className="review-card group" key={r.id}><div className="review-cover"><Image src={r.image} alt={r.title} fill sizes="240px" className="object-cover transition group-hover:scale-105"/></div><div className={`score ${r.score>=8?'high':r.score>=5?'mid':'low'}`}>{r.score}</div><div className="review-copy"><h3>{r.title}</h3><p>“{r.verdict}”</p><span className="muted">Reviewed by {r.reviewer}</span></div></Link>)}</div></div></section>}
export function Popular(){return <section className="wrap section"><SectionHead title="Popular games" label="PLAY RIGHT NOW"/><div className="popular-grid">{popularGames.map(g=><GameCard game={g} key={g.id}/>)}</div></section>}
export function Newsletter(){return <section className="newsletter wrap"><div><span className="eyebrow">THE WEEKLY DROP</span><h2>Never miss what&apos;s next.</h2><p>One sharp dispatch of the stories, games, and ideas worth your time.</p></div><form onSubmit={e=>e.preventDefault()}><label className="sr-only" htmlFor="email">Email address</label><div className="email-field"><Mail size={17}/><input id="email" type="email" placeholder="you@email.com" required/><button type="submit">Subscribe</button></div><small>By subscribing, you agree to our terms.</small></form></section>}
function SectionHead({title,label,href,controls}:{title:string;label?:string;href?:string;controls?:boolean}){return <div className="section-head"><div><span className="eyebrow accent">{label||'LATEST'}</span><h2>{title}</h2></div><div className="head-actions">{href&&<Link href={href} className="view-all">View all <ArrowUpRight size={15}/></Link>}{controls&&<div className="controls"><button aria-label="Previous"><ChevronLeft size={18}/></button><button aria-label="Next"><ChevronRight size={18}/></button></div>}</div></div>}
